<?php

/**
 * @file
 * Functions to support theming in the bewg theme.
 */

use Drupal\Core\Url;
use Drupal\media\Entity\Media;
use Drupal\file\Entity\File;
use Drupal\node\Entity\Node;

/**
 * Implements template_preprocess_html().
 */
function bewg_preprocess_html(&$variables) {
  if (!empty($variables['page']['sidebar_first'])) {
    $sidebar_left = $variables['page']['sidebar_first'];
  }

  if (!empty($variables['page']['sidebar_second'])) {
    $sidebar_right = $variables['page']['sidebar_second'];
  }

  // Dynamic sidebars.
  if (!empty($sidebar_left) && !empty($sidebar_right)) {
    $variables['attributes']['class'][] = 'two-sidebars';
  }
  elseif (empty($sidebar_left) && !empty($sidebar_right)) {
    $variables['attributes']['class'][] = 'one-sidebar';
    $variables['attributes']['class'][] = 'sidebar-second';
  }
  elseif (!empty($sidebar_left) && empty($sidebar_right)) {
    $variables['attributes']['class'][] = 'one-sidebar';
    $variables['attributes']['class'][] = 'sidebar-first';
  }
  else {
    $variables['attributes']['class'][] = 'no-sidebars';
  }
}

/**
 * Implements template_preprocess_page.
 */
function bewg_preprocess_page(&$variables) {

  // $site_name = \Drupal::configFactory()->get('system.site')->get('name');

  // $variables['linked_site_name'] = [
  //   '#type' => 'link',
  //   '#title' => $site_name,
  //   '#url' => Url::fromRoute('<front>'),
  // ];
  // $variables["background_url"] = "";

  if(isset($variables["node"]) && $variables["node"]->getType() == "page"){
    $targetId = $variables["node"]->field_background_image->target_id;
    $mediaEntity = Media::load($targetId);
    $fileEntity = File::load($mediaEntity->field_image->target_id);
    $variables["background_url"] = $fileEntity->createFileUrl();

  }else{
    $variables["background_url"] = "/sites/default/files/2020-12/bg-news.jpg";
  }

}

/**
 * Implements template_preprocess_node.
 */
function bewg_preprocess_node(&$variables) {
  // $variables['is_front'] = \Drupal::service('path.matcher')->isFrontPage();

  // if ($variables['is_front']) {
  //   $nids = \Drupal::entityQuery('node')->condition('type','front_caroussel_items')->execute();
  //   $nodes = Node::loadMultiple($nids);
  //   $variables['caroussel_items'] = [];
  //   foreach ($nodes as $node) {
  //     $url = file_create_url(
  //       File::load(
  //         $node->field_caroussel_image->getValue()[0]['target_id']
  //       )->uri->getValue()[0]['value']
  //     );

  //     array_push($variables['caroussel_items'], $url);
  //   }
  // }
}



