<?php

/**
 * @file
 * Functions to support theming in the bewg theme.
 */

use Drupal\Core\Url;
use Drupal\media\Entity\Media;
use Drupal\file\Entity\File;

/**
 * Implements template_preprocess_html().
 */
function bewg_preprocess_html(&$variables) {
  if (!empty($variables['page']['sidebar_first'])) {
    $sidebar_left = $variables['page']['sidebar_first'];
  }

  if (!empty($variables['page']['sidebar_second'])) {
    $sidebar_right = $variables['page']['sidebar_second'];
  }

  // Dynamic sidebars.
  if (!empty($sidebar_left) && !empty($sidebar_right)) {
    $variables['attributes']['class'][] = 'two-sidebars';
  }
  elseif (empty($sidebar_left) && !empty($sidebar_right)) {
    $variables['attributes']['class'][] = 'one-sidebar';
    $variables['attributes']['class'][] = 'sidebar-second';
  }
  elseif (!empty($sidebar_left) && empty($sidebar_right)) {
    $variables['attributes']['class'][] = 'one-sidebar';
    $variables['attributes']['class'][] = 'sidebar-first';
  }
  else {
    $variables['attributes']['class'][] = 'no-sidebars';
  }
}

/**
 * Implements template_preprocess_page.
 */
function bewg_preprocess_page(&$variables) {

  // $site_name = \Drupal::configFactory()->get('system.site')->get('name');

  // $variables['linked_site_name'] = [
  //   '#type' => 'link',
  //   '#title' => $site_name,
  //   '#url' => Url::fromRoute('<front>'),
  // ];
  // $variables["background_url"] = "";

  

  @$targetId = $variables["node"]->field_background_image->target_id;
  @$mediaEntity = Media::load($targetId);
  @$fileEntity = File::load($mediaEntity->field_image->target_id);
  
  $variables["background_url"] = $fileEntity->createFileUrl();

  
}

/**
 * Implements template_preprocess_node.
 */
function bewg_preprocess_node(&$variables) {
  
}

function bewg_preprocess_node__page(&$variables) {
 

}

